name: apple-documentation

include:
  - path: xcodegen/project.base.yml
    relativePaths: false

options:
  bundleIdPrefix: com.swiftty.apple-documentation
  developmentLanguage: ja

packages:
  AppleDocumentationPackage:
    path: AppleDocumentationPackage

targets:
  App:
    templates:
      - Application
    settings:
      base:
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.swiftty.apple-documentation.App-debug
          INFOPLIST_PREPROCESS: YES
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    scheme:
      testPlans:
        - path: App.xctestplan
          defaultPlan: true
    sources:
      - App
      - path: project.yml
        group: Configurations
        buildPhase: none
      - path: .swiftlint.yml
        group: Configurations
        buildPhase: none
      - path: App.xctestplan
        group: Configurations
        buildPhase: none
      - path: Configurations
        buildPhase: none
    dependencies:
      - package: AppleDocumentationPackage
        product: AppleDocumentationApp
    postBuildScripts:
      - name: Rename GoogleService-Info.plist
        script: |
          if [ "${CONFIGURATION}" == "Debug" ]; then
            cp "${PROJECT_DIR}/Configurations/debug/GoogleService-Info.plist" "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/GoogleService-Info.plist"
          fi
        inputFiles:
          - ${PROJECT_DIR}/Configurations/debug/GoogleService-Info.plist
        outputFiles:
          - ${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/GoogleService-Info.plist
      - name: Upload dSYMs to Crashlytics
        basedOnDependencyAnalysis: false
        script: |
          if [ "${CONFIGURATION}" == "Debug" ]; then
            "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
          fi
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Info.plist
          - ${TARGET_BUILD_DIR}/${EXECUTABLE_PATH}
          - ${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/GoogleService-Info.plist
