name: renovate-resolved

on:
  push:
    branches: [ "renovate/**" ]
    paths:
      - "AppleDocumentationPackage/Package.swift"

jobs:
  mac-os:
    runs-on: macos-26
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Update Package.resolved
        uses: swiftty/gha-commit-if-changed@main
        with:
          run: make resolve
          commit-message: "Update Package.resolved"
